---
- name: Run all the local playbooks
  hosts: localhost

- import_playbook: ./fedora/packages.yml
- import_playbook: ./fedora/rpmfusion.yml
- import_playbook: ./fedora/vscode.yml
- import_playbook: ./fedora/dotfiles.yml
