- name: Install packages
  hosts: localhost
  become: no
  tasks:
    - name: upgrade all packages
      package:
        name: "*"
        state: latest
      become: yes

    - name: install packages
      package: name={{ item }}
        state=present
      with_items:
        - bat
        - curl
        - fish
        - fzf
        - git
        - gnome-tweaks
        - htop
        - httpie
        - jless
        - fd-find
        - make
        - ncdu
        - neovim
        - podman
        - podman-compose
        - ripgrep
        - tig
        - tilix
        - util-linux-user
        - virt-manager
        - xclip
        - zsh
      become: yes

    - name: set zsh as default shell
      command: "usermod --shell /usr/bin/zsh {{ ansible_user_id }}"
      become: yes

    - debug: var=ansible_user_id
